M48
; DRILL file {KiCad 9.0.0} date 2025-03-23T00:29:21-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-23T00:29:21-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.020
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.500
%
G90
G05
T1
X132.985Y-92.2
X132.985Y-95.2
X132.985Y-98.2
T2
X138.8Y-95.0
X139.0Y-90.6
X139.0Y-99.4
M30
